name: schoolms
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.3.0
  envify: ^2.0.3
  geocoding: ^2.1.0
  location: ^5.0.3
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.3.3
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/